archives:
  - format: zip
builds:
  - main: ./src/
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    binary: 'terraform-provider-horizonview_v{{ .Version }}'
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
      - '^chore'
      - '^build'
      - '^docs'
      - '^sample-scripts'
