name: Build Provider
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Provider
        working-directory: ./src
        run: |
          if [ ${{ matrix.os }} == 'windows-latest' ]; then
            go build -o terraform-provider-horizonview.exe
          elif [ ${{ matrix.os }} == 'macos-latest' ]; then
            GOOS=darwin GOARCH=amd64 go build -o terraform-provider-horizonview
          else
            GOOS=linux GOARCH=amd64 go build -o terraform-provider-horizonview
          fi

      - name: Compress Build Artifacts
        run: |
          cd src
          if [ ${{ matrix.os }} == 'windows-latest' ]; then
            zip -r -9 terraform-provider-horizonview-${{ matrix.os }}.zip terraform-provider-horizonview.exe
          else
            zip -r -9 terraform-provider-horizonview-${{ matrix.os }}.zip terraform-provider-horizonview
          fi
          mv terraform-provider-horizonview-${{ matrix.os }}.zip ../

      - name: Upload Compressed Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: terraform-provider-horizonview-${{ matrix.os }}
          path: terraform-provider-horizonview-${{ matrix.os }}.zip
          
      - name: Test Code
        working-directory: ./src
        run: go test -o .terraform-provider-horizonview -json > TestResults-${{ matrix.os }}.json

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-${{ matrix.os }}
          path: src/TestResults-${{ matrix.os }}.json
