name: Build Provider
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install Dependencies
        run: |
          go mod tidy
          go mod download
        working-directory: ./src
        shell: bash

      - name: Build Provider
        run: |
          echo "Building provider for OS: ${{ matrix.os }}"
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            GOOS=windows GOARCH=amd64 go build -o terraform-provider-horizonview.exe
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            GOOS=darwin GOARCH=amd64 go build -o terraform-provider-horizonview
          else
            GOOS=linux GOARCH=amd64 go build -o terraform-provider-horizonview
          fi
        shell: bash
        working-directory: ./src

      - name: Compress Build Artifacts and Generate Checksum
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            zip -j terraform-provider-horizonview-linux_amd64.zip src/terraform-provider-horizonview
            sha256sum terraform-provider-horizonview-linux_amd64.zip | sed 's/ .*/ terraform-provider-horizonview-linux_amd64.zip/' >> checksums.txt
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            zip -j terraform-provider-horizonview-darwin_amd64.zip src/terraform-provider-horizonview
            shasum -a 256 terraform-provider-horizonview-darwin_amd64.zip | sed 's/ .*/ terraform-provider-horizonview-darwin_amd64.zip/' >> checksums.txt
          elif [[ "${{ runner.os }}" == "Windows" ]]; then
            Compress-Archive -Path src\terraform-provider-horizonview.exe -DestinationPath terraform-provider-horizonview-windows_amd64.zip
            # Use certutil to compute SHA256 checksum on Windows
            certutil -hashfile terraform-provider-horizonview-windows_amd64.zip SHA256 | findstr /v "hash" | sed 's/ .*/ terraform-provider-horizonview-windows_amd64.zip/' >> checksums.txt
          fi
        shell: bash

      - name: Upload Linux Build Artifacts
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: terraform-provider-horizonview-linux_amd64
          path: terraform-provider-horizonview-linux_amd64.zip

      - name: Upload macOS Build Artifacts
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: terraform-provider-horizonview-darwin_amd64
          path: terraform-provider-horizonview-darwin_amd64.zip

      - name: Upload Windows Build Artifacts
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: terraform-provider-horizonview-windows_amd64
          path: terraform-provider-horizonview-windows_amd64.zip

      - name: Upload Checksum File
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checksums
          path: checksums.txt
          
      - name: Test Code
        working-directory: ./src
        run: go test -o .terraform-provider-horizonview -json > TestResults-${{ matrix.os }}.json
        shell: bash

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-${{ matrix.os }}
          path: src/TestResults-${{ matrix.os }}.json

  
