name: Build Provider
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build Provider
        run: |
          echo "Building provider for OS: ${{ matrix.os }}"
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            go build -o terraform-provider-horizonview.exe
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            GOOS=darwin GOARCH=amd64 go build -o terraform-provider-horizonview
          else
            GOOS=linux GOARCH=amd64 go build -o terraform-provider-horizonview
          fi
        shell: bash
        working-directory: ./src
          
      - name: Compress Build Artifacts on Linux
        if: runner.os == 'Linux'
        run: |
          zip -j terraform-provider-horizonview-linux_amd64.zip src/terraform-provider-horizonview
          sha256sum terraform-provider-horizonview-linux_amd64.zip | sed 's/ .*/ terraform-provider-horizonview-linux_amd64.zip/' >> checksums.txt
        shell: bash

      - name: Compress Build Artifacts on macOS
        if: runner.os == 'macOS'
        run: |
          zip -j terraform-provider-horizonview-darwin_amd64.zip src/terraform-provider-horizonview
          shasum -a 256 terraform-provider-horizonview-darwin_amd64.zip | sed 's/ .*/ terraform-provider-horizonview-darwin_amd64.zip/' >> checksums.txt
        shell: bash

      - name: Compress Build Artifacts on Windows
        if: runner.os == 'Windows'
        run: |
          Compress-Archive -Path src\terraform-provider-horizonview.exe -DestinationPath terraform-provider-horizonview-windows_amd64.zip
          sha256sum terraform-provider-horizonview-windows_amd64.zip | sed 's/ .*/ terraform-provider-horizonview-windows_amd64.zip/' >> checksums.txt
        shell: pwsh

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: terraform-provider-horizonview-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            terraform-provider-horizonview-linux_amd64.zip
            terraform-provider-horizonview-darwin_amd64.zip
            terraform-provider-horizonview-windows_amd64.zip

      - name: Upload Checksum File
        uses: actions/upload-artifact@v4
        with:
          name: checksums
          path: checksums.txt
          
      - name: Test Code
        working-directory: ./src
        run: go test -o .terraform-provider-horizonview -json > TestResults-${{ matrix.os }}.json
        shell: bash

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-${{ matrix.os }}
          path: src/TestResults-${{ matrix.os }}.json
